---
- hosts: Router4
  connection: local
  gather_facts: no
  vars:
   host: "{{ ansible_host}}"
   username: user
   password: user
   transport: ssh

  tasks:
   - name: Define connection Provider
     set_fact:
       provider:
        username: user
        password: user
        auth_pass: user

   - name: configure loopback interface
     ios_config:
       provider: "{{ provider }}"
       lines:
         - description test interface
         - ip address 10.0.0.1 255.255.255.0
       parents: interface Loopback1
     register: interfaceLoopback1
   - debug: var=interfaceLoopback1
   - name: load new acl into device
     ios_config:
       provider: "{{ provider }}"
       lines:
         - 10 permit 192.168.85.5
       parents: ip access-list standard arctiq
       match: exact
